name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login \
        --username AWS \
        --password-stdin 640129503214.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build Docker image
      run: docker build -t genai-app .

    - name: Tag image
      run: docker tag genai-app:latest 640129503214.dkr.ecr.ap-south-1.amazonaws.com/genai-app:latest

    - name: Push image
      run: docker push 640129503214.dkr.ecr.ap-south-1.amazonaws.com/genai-app:latest

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ap-south-1 --name genai-cluster

    - name: Create OpenAI Secret
      run: |
        kubectl create secret generic openai-secret \
        --from-literal=OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
        --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml